config/routes.rb
Rails.application.routes.draw do
  get 'shows/index'
  resources :shows do
    resources :episodes
  end
  root 'welcome#index'

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/episodes_controller.rb
class EpisodesController < ApplicationController
  def index
  end

  def show
    @episode_id = params["id"].match(/s(\d+)e(\d+)/)
    @episode_season = @episode_id[1]
    @episode_number = @episode_id[2]
    response = HTTParty.get("http://epguides.frecar.no/show/#{params["show_id"]}/#{@episode_season}/#{@episode_number}")
    @episode = JSON.parse(response.body)
  end
end

app/controllers/shows_controller.rb
class ShowsController < ApplicationController
  def index
    response = HTTParty.get('http://epguides.frecar.no/show/')
    @shows = JSON.parse(response.body)
  end

  def show
    @id = params["id"]
    response = HTTParty.get("http://epguides.frecar.no/show/#{@id}")
    @seasons = JSON.parse(response.body)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/shows_helper.rb
module ShowsHelper
end

app/views/episodes/show.html.erb
<h1>Episode</h1>

<%= @episode %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Clickr</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/shows/index.erb
<h1>TV Shows</h1>

<ul>
  <% @shows.each do |show| %>
    <li>
      <%= link_to show["title"], show_path(show['epguide_name']) %>
    </li>
  <% end %>
</ul>

app/views/shows/show.erb
<h1>Show!</h1>
<%= @seasons.first.last[0].keys %>
<ul>
  <% @seasons.each do |season| %>
    <li>
      <strong>Season: <%= season.first %></strong>
      <ol>
        <% season.last.each do |episode| %>
          <li>
            <%= link_to episode["title"], show_episode_path(episode['show']['epguide_name'], "s#{episode['season']}e#{episode['number']}") %>
            <%= episode["release_date"] %>
            <ul>
              <li>
                <%= episode["show"] %>
              </li>
            </ul>
          </li>
        <% end %>
      </ol>
    </li>
  <% end %>
</ul>